version: 0.2 

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
  build:
    commands:
      - echo "Current working directory is $(pwd)"
      - echo "Listing contents of the current directory for debug purposes..."
      - ls -lah
      - |
        DOCKERFILE_PATH="vendor/laravel/sail/runtimes/8.2/Dockerfile"
        echo "Checking for Dockerfile at $DOCKERFILE_PATH..."
        if [ -f "$DOCKERFILE_PATH" ]; then
          echo "Dockerfile found, proceeding with build..."
          docker build -f $DOCKERFILE_PATH -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/my-custom-laravel-image:latest .
        else
          echo "Dockerfile not found at $DOCKERFILE_PATH, aborting build."
          exit 1
        fi
  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/my-custom-laravel-image:latest
      - echo "Build and push completed on $(date)"
