version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - echo "AWS CLI version:"
      - aws --version
      - echo "Checking AWS_DEFAULT_REGION:"
      - echo ${AWS_DEFAULT_REGION}
      - echo "Checking AWS_ACCOUNT_ID:"
      - echo ${AWS_ACCOUNT_ID}
      - echo "Attempting to login to ECR with debug information..."
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/easymarket-backend
      - echo "REPOSITORY_URI is set to ${REPOSITORY_URI}"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "IMAGE_TAG is set to ${IMAGE_TAG}"
  build:
    commands:
      - echo "Current working directory is $(pwd)"
      - echo "Listing contents of the current directory for debug purposes..."
      - ls -lah
      - echo "Building the Docker image from custom Dockerfile..."
      - |
        DOCKERFILE_PATH="vendor/laravel/sail/runtimes/8.2/Dockerfile"
        if [ -f "$DOCKERFILE_PATH" ]; then
          docker build -f $DOCKERFILE_PATH -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/my-custom-laravel-image:latest .
        else
          echo "Dockerfile not found at $DOCKERFILE_PATH"
          exit 1
        fi  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/my-custom-laravel-image:latest
      - echo "Build and push completed on $(date)"