version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo "Starting Docker Compose build and up..."
      - |
        # 環境変数を介してビルドコンテキストのパスを動的に設定
        export BUILD_CONTEXT_PATH="$(pwd)/vendor/laravel/sail/runtimes/8.2"
        sed -i "s|context: ./vendor/laravel/sail/runtimes/8.2|context: ${BUILD_CONTEXT_PATH}|g" docker-compose.yml
      - docker-compose -f docker-compose.yml up -d --build
  post_build:
    commands:
      - echo "Build and deployment completed on $(date)"
