name: Mirror AWS CodeCommit

on: [push]

jobs:
    mirror:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Push to AWS CodeCommit
        run: git push --mirror https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/easymarket-backend
  