name: Mirroring

on: [ push, delete ]

jobs:
  to_codecommit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/easymarket-backend
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_username:
            ${{ secrets.SSH_KEY_ID }}