name: Mirror AWS CodeCommit3

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      
      - name: Setup SSH and push with debug info
        env:
          GIT_SSH_COMMAND: ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
        run: |
          git remote set-url origin ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/easymarket-backend
          git push --mirror
